### ISSUE TITLE
Is ``RelaxCommand`` a Mixin or Dependency Injection?

### ISSUE THREAD

**Issue by adam-grant-hendry** [zanieb/poetry-relax#46]
I understand why ``RelaxCommand`` inherits from ``InstallerCommand`` (to use ``poetry`` ``Installer`` when running ``check``, ``update``, or ``lock``), but why does it also inherit from ``InitCommand``? Is this class a dependency injection of sorts? I don't see any internal methods from ``InitCommand`` used in this class.

**Comment by zanieb** [comment]
I don't remember! But I'll take a look when I get the chance and let you know.

**Comment by zanieb** [comment]
I presumed this was for an older version of Poetry, but since #48 passes CI it just looks unused. Likely an artifact from earlier in development, thanks for pointing it out!
