### ISSUE TITLE
BUG: `list` Multiple Constraint Dependencies Not Supported

### ISSUE THREAD

**Issue by adam-grant-hendry** [zanieb/poetry-relax#47]
`poetry` supports [multiple constraint dependencies](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies) provided as arrays of inline tables in TOML (i.e. lists of dictionaries in Python):

```toml
[tool.poetry.dependencies]
foo = [
    {version = "<=1.9", python = ">=3.6,<3.8"},
    {version = "^2.0", python = ">=3.8"}
]
```

The [current source](https://github.com/zanieb/poetry-relax/blob/cd2b4a8f39de6c04d58d09b691891ab4341abc60/src/poetry_relax/command.py#L162) errors in parsing these, leading to the following error when attempting to use the plugin with such a dependency:

```
'list' object has no attribute 'name'
```

To fix this, please use the method in [the current `poetry` source](https://github.com/python-poetry/poetry-core/blob/ca962a096b1a1f62008d75cfaca156d1ec2bfb65/src/poetry/core/factory.py#L96C13-L99C45):

```python
_constraints = constraints if isinstance(constraints, list) else [constraints]  # Convert to list

for _constraint in _constraints:  # Iterate through each item in constraint list
    # Now parse dictionaries in list
```

**Comment by zanieb** [comment]
👍 thanks for the report.

Are you interested in opening a pull request or would you rather I address it?

**Comment by adam-grant-hendry** [comment]
Only thing I don't know how to do yet is handle recombining the constraints again into one multi-constraint. e.g. `foo` in the above gets 2 entries in `target_entries` if you do:

```python
target_dependencies: List[Dependency] = []
for group in groups:
    ...
    for name, constraints in dependency_config.items():
        if isinstance(constraints, list):
            _constraints = constraints
        else:
            _constraints = [constraints]

        for _constraint in _constraints:
            target_dependencies.append(
                Factory.create_dependency(name, _constraint)
            )
```

If you print out `target_dependencies`, you'll get:

```python
[<Dependency foo (<=1.9)>,
 <Dependency foo (>=2.0, <3.0),
]
```

I'm trying to read the `poetry` source now to find out how they do it...
```

**Comment by adam-grant-hendry** [comment]
@zanieb I don't see that `poetry` does anything in particular. I think this should work (starting at [line 266](https://github.com/zanieb/poetry-relax/blob/cd2b4a8f39de6c04d58d09b691891ab4341abc60/src/poetry_relax/command.py#L266) in the current source):

```python
for group in groups:
    dependency_config = extract_dependency_config_for_group(
        group, poetry_config
    )
    if dependency_config is None:
        continue

    for old_constraint, dependency in updated_dependencies[group]:
        # Mutate the dependency config (and consequently the pyproject config)
        name = dependency.name
        version = dependency.pretty_constraint

        constraints = dependency_config[name]

        # Support multiple constraint dependencies
        if isinstance(constraints, list):
            for ndx, _constraint in enumerate(constraints):
                if isinstance(_constraint, dict):
                    dependency_config[name][ndx]['version'] = version
                else:
                    dependency_config[name][ndx] = version
        else:
            if isinstance(constraints, dict):
                dependency_config[name]['version'] = version
            else:
                dependency_config[name] = version

        # Display the final updates since they can be buried by the installer update
        self.info(
            f"Updated <c1>{dependency.pretty_name}</> constraint from "
            f"<c2>{old_constraint}</> to <c2>{dependency.pretty_constraint}</>"
            f"{_pretty_group(group)}"
        )
```

**Comment by adam-grant-hendry** [comment]
>👍 thanks for the report.
>
> Are you interested in opening a pull request or would you rather I address it?

My pleasure. If you want to make the changes I suggested, I'd rather you address it if that's alright.

**Comment by zanieb** [comment]
No problem, I'll look into it. Thanks for taking the time to research it!

**Comment by zanieb** [comment]
Here's a failing test https://github.com/zanieb/poetry-relax/commit/11a4f28f300fa3ecdfa875798169cb3d35553fc8 — although it does not fail with the error you described so I may have set it up wrong.

**Comment by zanieb** [comment]
#52 resolves this if you're interested in reviewing!

**Comment by adam-grant-hendry** [comment]
> #52 resolves this if you're interested in reviewing!

Thank you! Love your fast response (you're a great maintainer)
