### ISSUE TITLE
[BUG]: Fixture `seeded_project_venv` Fails on Windows

### ISSUE THREAD

**Issue by adam-grant-hendry** [zanieb/poetry-relax#60]
As the title states, [this fixture fails](https://github.com/zanieb/poetry-relax/blob/f92defb9460e4a047a75f2c6f26d8b817ea7de40/tests/_fixtures.py#L240) on Windows since the path to the Python executable on Windows machines is `Scripts\python.exe`.

Can we please change the code to:

```python
import sys
...
def seeded_project_venv(
    seeded_poetry_project_path: Path,
    poetry_application_factory: PoetryApplication,
) -> VirtualEnv:
    if sys.platform == 'win32':
        executable = seeded_poetry_project_path / ".venv" / "Scripts" / "python.exe"
    else:
        executable = seeded_poetry_project_path / ".venv" / "bin" / "python"
```

**Comment by zanieb** [comment]
Hm development on Windows isn't currently supported — is this only thing needed for tests to pass?

**Comment by adam-grant-hendry** [comment]
Once I manually changed it, all the tests did pass with the current release, yes.

**Comment by adam-grant-hendry** [comment]
If the virtual environment is activated in the test, using `sys.executable` instead should work.

**Comment by zanieb** [comment]
Sweet I'm glad things work on Windows without any additional portability. I'll look into adding coverage in CI.

`sys.executable` would be the Python executable of the test runner process which isn't in the virtual environment which is why we have to manually construct the path.

**Comment by adam-grant-hendry** [comment]
Ah, excellente, I get it. Can I submit a small PR for this? I’d just do an `if-else` check on `sys.platform`.

**Comment by zanieb** [comment]
👍 sounds great
